name: fitness_tracker
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0

  # Step counter
  pedometer: ^4.0.1

  # Notifications
  flutter_local_notifications: ^17.0.0

  # PDF export
  pdf: ^3.10.7
  printing: ^5.12.0

  # File path
  path_provider: ^2.1.2

  # Hive local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Hive code generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
